### ISSUE TITLE
There's something wrong with my code

### ISSUE THREAD

**Issue by leexk312** [DanielLin97/ACLR4RUMOR-NAACL2022#1]
Hello! When I run your code by "CUDA_VISIBLE_DEVICES=0 python ./model/Weibo/ACLR_Weibo.py Weibo 1" ,there's a FileNotFoundError:"[Errno 2] No such file or directory: '/home/bigdata13/lxk/ACLR4RUMOR-NAACL2022-main/data/Twittergraph/692098463262216192.npz'" and the directory /Twittergraph/ is empty. How can I generate the File? Looking forward to your answer,Thank you.

**Comment by DanielLin97** [comment]
Please kindly look into the Readme for the precomputed XLM-R representations and graph construction of the datasets: https://github.com/DanielLin97/ACLR4RUMOR-NAACL2022/blob/main/data/README.md

Hope it helpful for your issue.

**Comment by leexk312** [comment]
Thx for you answer,I've read it carefully but I don't know how to use getWeibograph.py to generate Twitter dataset's XLM-R representations and graph construction.

**Comment by DanielLin97** [comment]
> Thx for you answer,I've read it carefully but I don't know how to use getWeibograph.py to generate Twitter dataset's XLM-R representations and graph construction.



> Thx for you answer,I've read it carefully but I don't know how to use getWeibograph.py to generate Twitter dataset's XLM-R representations and graph construction.

You could simply change the relative path of Weibo-COVID19 data (#Line 104, 120, 149, 158) into that of TWITTER data in the main func of the getWeibograph.py file and then run the code. Or you could directly download them from: https://www.dropbox.com/sh/raz6unw2lswcy54/AADNsc-ifBoAfN1wwyVvgch-a?dl=0

**Comment by leexk312** [comment]
Ok .Thank you for your patient answer!
