### ISSUE TITLE
There's something wrong with my code#5

### ISSUE THREAD

**Issue by baiw123** [DanielLin97/ACLR4RUMOR-NAACL2022#3]
Hello, when I run your code by "python ./Process/getWeibograph.py Twitter", how can I get the files in Weibograph? Looking forward to your answer, thank you.

**Comment by TpBlair** [comment]
you can write by yourself.

**Comment by DanielLin97** [comment]
Yeah, it's similar to the getTwitter file. it is straightforwardly to obtain the related files. or you could download the files from the links I posted.

**Comment by DanielLin97** [comment]
yeah, you could run the code for the related files or you could just straightforwardly download the files from the links I posted.

**Comment by TpBlair** [comment]
traindata_list, testdata_list = loadBiData(dataname, treeDic, x_train, x_test, TDdroprate,BUdroprate)
twitterdata_list = loadBiData(dataname='Weibo', treeDic=treeDic, fold_x_train=twitter_train, fold_x_test=[], TDdroprate=TDdroprate, BUdroprate=BUdroprate)

treeDic?????????????????????????????????????

**Comment by DanielLin97** [comment]
> traindata_list, testdata_list = loadBiData(dataname, treeDic, x_train, x_test, TDdroprate,BUdroprate) twitterdata_list = loadBiData(dataname='Weibo', treeDic=treeDic, fold_x_train=twitter_train, fold_x_test=[], TDdroprate=TDdroprate, BUdroprate=BUdroprate)
> 
> treeDic?????????????????????????????????????

sorry, could you please present your question more precisely about that point?

**Comment by baiw123** [comment]
> yeah, you could run the code for the related files or you could just straightforwardly download the files from the links I posted.

Thanks for your answer, the file I downloaded from  https://www.dropbox.com/s/46r50ctrfa0ur1o/rumdect.zip?dl=0. is not a txt file or an npz file, I don't know how to use it.

**Comment by DanielLin97** [comment]
> > yeah, you could run the code for the related files or you could just straightforwardly download the files from the links I posted.
> 
> Thanks for your answer, the file I downloaded from https://www.dropbox.com/s/46r50ctrfa0ur1o/rumdect.zip?dl=0. is not a txt file or an npz file, I don't know how to use it.
actually it's the raw datasets.
please download the processed files from the link I posted in the README at https://github.com/DanielLin97/ACLR4RUMOR-NAACL2022/tree/main/data

**Comment by DanielLin97** [comment]
> > yeah, you could run the code for the related files or you could just straightforwardly download the files from the links I posted.
> 
> Thanks for your answer, the file I downloaded from https://www.dropbox.com/s/46r50ctrfa0ur1o/rumdect.zip?dl=0. is not a txt file or an npz file, I don't know how to use it.

actually it's the raw datasets.
please download the processed files from the link I posted in the README at https://github.com/DanielLin97/ACLR4RUMOR-NAACL2022/tree/main/data

**Comment by baiw123** [comment]
> > > yeah, you could run the code for the related files or you could just straightforwardly download the files from the links I posted.
> > 
> > 
> > Thanks for your answer, the file I downloaded from https://www.dropbox.com/s/46r50ctrfa0ur1o/rumdect.zip?dl=0. is not a txt file or an npz file, I don't know how to use it.
> 
> actually it's the raw datasets. please download the processed files from the link I posted in the README at https://github.com/DanielLin97/ACLR4RUMOR-NAACL2022/tree/main/data

Thx for you answer,but I can't find the processed file at https://github.com/DanielLin97/ACLR4RUMOR-NAACL2022/tree/main/data/Weibo/WEIBO

**Comment by DanielLin97** [comment]
> > > > yeah, you could run the code for the related files or you could just straightforwardly download the files from the links I posted.
> > > 
> > > 
> > > Thanks for your answer, the file I downloaded from https://www.dropbox.com/s/46r50ctrfa0ur1o/rumdect.zip?dl=0. is not a txt file or an npz file, I don't know how to use it.
> > 
> > 
> > actually it's the raw datasets. please download the processed files from the link I posted in the README at https://github.com/DanielLin97/ACLR4RUMOR-NAACL2022/tree/main/data
> 
> Thx for you answer,but I can't find the processed file at https://github.com/DanielLin97/ACLR4RUMOR-NAACL2022/tree/main/data/Weibo/WEIBO

you can download all the processed files from the links I posted in README, not just in WEIBO.

**Comment by baiw123** [comment]
Ok .Thank you for your patient answer!
