### ISSUE TITLE
weibo-covid19 dataset has an error!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by TpBlair** [DanielLin97/ACLR4RUMOR-NAACL2022#5]
![image](https://github.com/DanielLin97/ACLR4RUMOR-NAACL2022/assets/51107495/e41269c6-ea04-4950-be84-1e48f175e9f3)
![image](https://github.com/DanielLin97/ACLR4RUMOR-NAACL2022/assets/51107495/8d181ede-36d8-4c1d-9125-0a715fb12b24)

Hello, the timestamp of your data set is wrong and it is actually a negative number. Could you please correct it?

**Comment by TpBlair** [comment]
Why is the above problem not solved? I am a little skeptical about your early detection experiment?

**Comment by DanielLin97** [comment]
Note that the timestamp is used for the Twitter-COVID19 data for the related experiment. It's just a placeholder for Weibo-COVID19, which is not used. If you are interested in the timestamp of Weibo-COVID19, you can straightforwardly collect them through Weibo API.

**Comment by DanielLin97** [comment]
> Why is the above problem not solved? I am a little skeptical about your early detection experiment?

FYI, in terms of Twitter-COVID19, you can crawl the related metadata via Twitter academic API with a twarc2 python package (https://twarc-project.readthedocs.io/en/latest/twarc2_en_us/) according to the event id. Hope it helps.
